# Introduction

Sarcasm is a sophisticated language phenomenon, which would cause much confusion to exist sentiment classification systems.     
So sarcasm detection, a task of predicting whether a given text contains sarcasm, has received much research attention.     

Recently, many methods have been proposed for sarcasm detection, which could be broadly classified into two categories.     
One is the text-only method which only concentrate on the utterance itself, such as exploiting incongruity expressions to detect the sarcasm text.     
Another direction is based on extra information, which exploits external knowledge to assist the detection procedure, such as user history, and common sense knowledge.

We propose an unsupervised sarcasm detection method.     

First, we leverage the external sentiment knowledge to mask prominent tokens. Then the masked texts are fed into the pre-trained generation model, which follows the remaining logic structure to generate texts.     
There is a good chance that these reborn texts would not be sarcastic or make more sense.     

Second, after obtaining the similarity score between the generated sentence and the original one, features beneath the scores will be extracted to decide whether a sentence is sarcasm.     

Then, we construct several unsupervised baselines and conduct experiments on IAC-V2 dataset.

# Imports and Reading Data

In [ ]:
!pip install senticnet

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.9/51.9 MB 32.7 MB/s eta 0:00:00


In [ ]:
import numpy as np
import pandas as pd

from senticnet.senticnet import SenticNet

import nltk
from nltk.corpus import stopwords
nltk.download('punkt')
nltk.download('stopwords')
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

from transformers import AutoTokenizer, AutoModel
from transformers import BartTokenizer, BartForConditionalGeneration
import torch

from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics import accuracy_score, precision_score, f1_score
from sklearn.metrics import confusion_matrix

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df = pd.read_csv("/content/drive/My Drive/AlifResearch/iSarcasm/train.csv")
df1 = pd.read_csv("/content/drive/My Drive/AlifResearch/iSarcasm/test.csv")

In [ ]:
df

id                                               text  label emoji  \
0        1  why do small shouldered tiny guys wear huge t ...      0   NaN   
1        2  good morning , please go and vote ! <repeated>...      0     🙅   
2        3  is it even christmas if there isn ’ t a fight ...      1   NaN   
3        4  helping mum with her maths work for the course...      0   NaN   
4        5  <hashtag> dear customer </hashtag> i am sorry ...      0   NaN   
...    ...                                                ...    ...   ...   
3111  3112  fcking hate being let down . don ’ t get my ho...      0   NaN   
3112  3113                          last day in my twenties 😫      0     😫   
3113  3114    who ’ s dick do i have to suck for some dominos      0   NaN   
3114  3115  <user> yet if you threw cold water it would st...      0   NaN   
3115  3116  change your pin guys ! <repeated> monzo custom...      0   NaN   

                                                 tag  
0                                                NaN  
1     <url>,</hashtag>,<hashtag>,<number>,<repeated>  
2                                                NaN  
3                                                NaN  
4                               <hashtag>,</hashtag>  
...                                              ...  
3111                                             NaN  
3112                                             NaN  
3113                                             NaN  
3114                                          <user>  
3115                                <url>,<repeated>  

[3116 rows x 5 columns]

In [ ]:
df1

id                                               text  label emoji  \
0    3464  saw poppin fresh in the macy ' s parade . my d...      1   NaN   
1    3465  i knew as soon as i heard doing ford was cutti...      0   NaN   
2    3466  great advice from well established individuals...      0   NaN   
3    3467  eating apple sauce , chicken thighs , broccoli...      0   NaN   
4    3468  <user> ur not a real smiler if ur not expectin...      1   NaN   
..    ...                                                ...    ...   ...   
882  4346  imagine that it ' s going to cost me <number> ...      0   NaN   
883  4347  people really out here tryna argue you do not ...      0   NaN   
884  4348  <user> and their relentless running game , on ...      0   NaN   
885  4349  why is it that whether i get out of bed at <nu...      0   NaN   
886  4350  honestly this morning ’ s news about gavin and...      0     ❤   

                                          tag  
0                                         NaN  
1                             <url>,<percent>  
2                                      <user>  
3                        <hashtag>,</hashtag>  
4                                      <user>  
..                                        ...  
882                                  <number>  
883                                     <url>  
884                           <number>,<user>  
885  <number>,<allcaps>,<repeated>,</allcaps>  
886                                       NaN  

[887 rows x 5 columns]

In [ ]:
# Concatenate vertically
df = pd.concat([df, df1], ignore_index=True)
df

id                                               text  label emoji  \
0        1  why do small shouldered tiny guys wear huge t ...      0   NaN   
1        2  good morning , please go and vote ! <repeated>...      0     🙅   
2        3  is it even christmas if there isn ’ t a fight ...      1   NaN   
3        4  helping mum with her maths work for the course...      0   NaN   
4        5  <hashtag> dear customer </hashtag> i am sorry ...      0   NaN   
...    ...                                                ...    ...   ...   
3998  4346  imagine that it ' s going to cost me <number> ...      0   NaN   
3999  4347  people really out here tryna argue you do not ...      0   NaN   
4000  4348  <user> and their relentless running game , on ...      0   NaN   
4001  4349  why is it that whether i get out of bed at <nu...      0   NaN   
4002  4350  honestly this morning ’ s news about gavin and...      0     ❤   

                                                 tag  
0                                                NaN  
1     <url>,</hashtag>,<hashtag>,<number>,<repeated>  
2                                                NaN  
3                                                NaN  
4                               <hashtag>,</hashtag>  
...                                              ...  
3998                                        <number>  
3999                                           <url>  
4000                                 <number>,<user>  
4001        <number>,<allcaps>,<repeated>,</allcaps>  
4002                                             NaN  

[4003 rows x 5 columns]

In [ ]:
df = df.drop(columns=['id', 'emoji', 'tag'])
df

text  label
0     why do small shouldered tiny guys wear huge t ...      0
1     good morning , please go and vote ! <repeated>...      0
2     is it even christmas if there isn ’ t a fight ...      1
3     helping mum with her maths work for the course...      0
4     <hashtag> dear customer </hashtag> i am sorry ...      0
...                                                 ...    ...
3998  imagine that it ' s going to cost me <number> ...      0
3999  people really out here tryna argue you do not ...      0
4000  <user> and their relentless running game , on ...      0
4001  why is it that whether i get out of bed at <nu...      0
4002  honestly this morning ’ s news about gavin and...      0

[4003 rows x 2 columns]

In [ ]:
df['class'] = df['label'].map({0: 'notsarc', 1: 'sarc'})
df

text  label    class
0     why do small shouldered tiny guys wear huge t ...      0  notsarc
1     good morning , please go and vote ! <repeated>...      0  notsarc
2     is it even christmas if there isn ’ t a fight ...      1     sarc
3     helping mum with her maths work for the course...      0  notsarc
4     <hashtag> dear customer </hashtag> i am sorry ...      0  notsarc
...                                                 ...    ...      ...
3998  imagine that it ' s going to cost me <number> ...      0  notsarc
3999  people really out here tryna argue you do not ...      0  notsarc
4000  <user> and their relentless running game , on ...      0  notsarc
4001  why is it that whether i get out of bed at <nu...      0  notsarc
4002  honestly this morning ’ s news about gavin and...      0  notsarc

[4003 rows x 3 columns]

In [ ]:
# Drop the old 'label' column and rename 'tweet' to 'text'
df = df.drop(columns=['label'])
df = df.rename(columns={'tweet': 'text'})

In [ ]:
df

text    class
0     why do small shouldered tiny guys wear huge t ...  notsarc
1     good morning , please go and vote ! <repeated>...  notsarc
2     is it even christmas if there isn ’ t a fight ...     sarc
3     helping mum with her maths work for the course...  notsarc
4     <hashtag> dear customer </hashtag> i am sorry ...  notsarc
...                                                 ...      ...
3998  imagine that it ' s going to cost me <number> ...  notsarc
3999  people really out here tryna argue you do not ...  notsarc
4000  <user> and their relentless running game , on ...  notsarc
4001  why is it that whether i get out of bed at <nu...  notsarc
4002  honestly this morning ’ s news about gavin and...  notsarc

[4003 rows x 2 columns]

In [ ]:
import re
# Function to remove text inside <>
def remove_brackets(text):
    return re.sub(r'<.*?>', '', text).strip()

# Apply the function to the 'text' column
df['text'] = df['text'].apply(remove_brackets)
df

text    class
0     why do small shouldered tiny guys wear huge t ...  notsarc
1     good morning , please go and vote !  it only t...  notsarc
2     is it even christmas if there isn ’ t a fight ...     sarc
3     helping mum with her maths work for the course...  notsarc
4     dear customer  i am sorry that the mobile phon...  notsarc
...                                                 ...      ...
3998  imagine that it ' s going to cost me  pound to...  notsarc
3999  people really out here tryna argue you do not ...  notsarc
4000  and their relentless running game , on the bri...  notsarc
4001  why is it that whether i get out of bed at  or...  notsarc
4002  honestly this morning ’ s news about gavin and...  notsarc

[4003 rows x 2 columns]

In [ ]:
!pip install emoji

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 431.4/431.4 kB 26.2 MB/s eta 0:00:00


In [ ]:
import emoji
# Function to remove emojis
def remove_emojis(text):
    return emoji.replace_emoji(text, replace='')

# Apply the function to the 'text' column
df['text'] = df['text'].apply(remove_emojis)
df

text    class
0     why do small shouldered tiny guys wear huge t ...  notsarc
1     good morning , please go and vote !  it only t...  notsarc
2     is it even christmas if there isn ’ t a fight ...     sarc
3     helping mum with her maths work for the course...  notsarc
4     dear customer  i am sorry that the mobile phon...  notsarc
...                                                 ...      ...
3998  imagine that it ' s going to cost me  pound to...  notsarc
3999  people really out here tryna argue you do not ...  notsarc
4000  and their relentless running game , on the bri...  notsarc
4001  why is it that whether i get out of bed at  or...  notsarc
4002  honestly this morning ’ s news about gavin and...  notsarc

[4003 rows x 2 columns]

# Understanding Data

In [ ]:
df.dtypes

text     object
class    object
dtype: object

In [ ]:
df.columns

Index(['text', 'class'], dtype='object')

In [ ]:
text_data_original = list(df['text'])
text_data = [x.lower() for x in text_data_original]
print(*text_data, sep = "\n")

why do small shouldered tiny guys wear huge t shirts ?
good morning , please go and vote !  it only takes  minutes and a low turnout will hand victory to the brexit party   e uelections 2019
is it even christmas if there isn ’ t a fight with neighbours and a broken wrist ?
helping mum with her maths work for the course she ’ s taking and i ’ m slowly realising i am not great at maths
dear customer  i am sorry that the mobile phone reseller in the mall fucked you over . we all are not a bunch of sheisters . i hope your other life issues gets better and that i earned your future business .
anyone fancy writing my lit review for me ? can not . be . arsed .
so the  episode about ladonna was one of the most poignant and sad investigations of abuse of power and discrimination in institutions . v hard to listen to but so important .
middle aged women are bitchier than most people i know
baby tobias has arrived ! i ’ ll be taking a spot of leave but back into the swing of things for spring / s

In [ ]:
label_data = list(df['class'])
print(*label_data, sep = "\n")

notsarc
notsarc
sarc
notsarc
notsarc
notsarc
notsarc
notsarc
notsarc
notsarc
notsarc
notsarc
sarc
sarc
notsarc
notsarc
notsarc
notsarc
notsarc
notsarc
notsarc
notsarc
sarc
notsarc
notsarc
notsarc
notsarc
sarc
sarc
sarc
notsarc
notsarc
notsarc
notsarc
notsarc
notsarc
notsarc
sarc
notsarc
sarc
notsarc
notsarc
notsarc
notsarc
sarc
sarc
notsarc
sarc
notsarc
notsarc
notsarc
notsarc
notsarc
sarc
notsarc
notsarc
notsarc
sarc
notsarc
notsarc
notsarc
notsarc
sarc
notsarc
notsarc
notsarc
sarc
notsarc
notsarc
notsarc
notsarc
notsarc
sarc
notsarc
sarc
notsarc
notsarc
sarc
sarc
notsarc
notsarc
notsarc
notsarc
notsarc
sarc
notsarc
notsarc
notsarc
sarc
notsarc
notsarc
notsarc
notsarc
notsarc
sarc
sarc
notsarc
notsarc
notsarc
notsarc
sarc
notsarc
notsarc
notsarc
notsarc
notsarc
notsarc
notsarc
notsarc
notsarc
notsarc
notsarc
notsarc
notsarc
notsarc
notsarc
notsarc
notsarc
notsarc
notsarc
notsarc
notsarc
notsarc
notsarc
notsarc
notsarc
notsarc
notsarc
notsarc
notsarc
notsarc
notsarc
notsarc
notsarc
not

# Overview

The proposed framework contains three main components:     

1) Sentences mask and generation.     
This procedure first recognizes main components of sentences which will be properly masked to cause more impact on original sentences, and then fulfills the texts generation work;     

2) Sentences representation.     
It is expected to calculate dense vectors of sentences;     

3) Sarcastic utterances detection leverages.     
the similarity scores between original and regenerated sentences to detect whether an utterance is sarcastic.

# Sentences Mask and Generation
## 1)
"First, we use the sentiment common knowledge retrieved from SenticNet to recognize affective words in the sentence 𝑥,     
and split those words into two sets according to its sentiment polarities:    
PW = {pw1, pw2, ..., pwh} and    
NW = {nw1, nw2, ..., nwk},     
h + k <= n."

In [ ]:
def tokenize_sentence(sentence):
    tokens = word_tokenize(sentence)

    lemmatizer = WordNetLemmatizer()

    clean_tokens = []
    for tok in tokens:
        clean_tok = lemmatizer.lemmatize(tok).lower().strip()
        clean_tokens.append(clean_tok)

    return clean_tokens

In [ ]:
def get_sentiment_polarity_from_senticnet(word):
    sn = SenticNet()

    word = word.lower()

    try:
        return sn.polarity_label(word)
    except:
        return "neutral"

In [ ]:
def analyze_sentiment(sentences):
    positive_words = []
    negative_words = []

    for sentence in sentences:
        words = tokenize_sentence(sentence)

        PW = set()
        NW = set()

        for word in words:
            sentiment_polarity = get_sentiment_polarity_from_senticnet(word)
            if sentiment_polarity == "positive":
                PW.add(word.lower())
            elif sentiment_polarity == "negative":
                NW.add(word.lower())

        positive_words.append(PW)
        negative_words.append(NW)

    return positive_words, negative_words

In [ ]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [ ]:
positive_words, negative_words = analyze_sentiment(text_data)

for i, sentence in enumerate(text_data):
    print(f"Sentence: {sentence}")
    print(f"Positive Words: {positive_words[i]}")
    print(f"Negative Words: {negative_words[i]}")
    print("- - - - - - - - - -")

Streaming output truncated to the last 5000 lines.
Sentence: the one thing i wish i ’ d brought travelling with me is multi vitamins ! budget backpacking is not great for getting a balanced diet .
Positive Words: {'backpacking', 'brought', 'multi', 'great', 'travelling'}
Negative Words: {'vitamin'}
- - - - - - - - - -
Sentence: win a cyberpower  gaming pc plus  fifa   on pc .  ,  ,
Positive Words: {'win', 'gaming', 'fifa', 'plus'}
Negative Words: set()
- - - - - - - - - -
Sentence: i cannot wait for halloween        
Positive Words: set()
Negative Words: {'wait'}
- - - - - - - - - -
Sentence: thought i ' d be a sheep . it ' s yanny for me
Positive Words: set()
Negative Words: set()
- - - - - - - - - -
Sentence: bored of all these manager rumors .  viera , arteta and gerrard ? are these the guys to replace rafa or mo diame ?  nufc
Positive Words: {'rumor'}
Negative Words: {'bored'}
- - - - - - - - - -
Sentence: note to self .  the cold air is not good with asthma , bronchitis and a ches

In [ ]:
df["PW"] = positive_words
df["NW"] = negative_words
df

text    class  \
0     why do small shouldered tiny guys wear huge t ...  notsarc   
1     good morning , please go and vote !  it only t...  notsarc   
2     is it even christmas if there isn ’ t a fight ...     sarc   
3     helping mum with her maths work for the course...  notsarc   
4     dear customer  i am sorry that the mobile phon...  notsarc   
...                                                 ...      ...   
3998  imagine that it ' s going to cost me  pound to...  notsarc   
3999  people really out here tryna argue you do not ...  notsarc   
4000  and their relentless running game , on the bri...  notsarc   
4001  why is it that whether i get out of bed at  or...  notsarc   
4002  honestly this morning ’ s news about gavin and...  notsarc   

                                   PW                       NW  
0           {shirt, huge, wear, tiny}                       {}  
1     {victory, party, turnout, good}                    {low}  
2           {christmas, fight, wrist}                 {broken}  
3         {work, slowly, math, great}                    {mum}  
4                      {better, hope}          {fucked, sorry}  
...                               ...                      ...  
3998         {travel, imagine, pound}                   {cost}  
3999                               {}                  {argue}  
4000                  {army, running}  {dangerous, relentless}  
4001                               {}                       {}  
4002  {honestly, thrilled, favourite}             {television}  

[4003 rows x 4 columns]

## 2)
"Second, we analyze the sentence to get its syntax information to identify non-stop words     
     𝑆𝑊 = {𝑠𝑤1, 𝑠𝑤2, ..., 𝑠𝑤𝑚, 𝑚 ≤ 𝑛}.     
Intuitively, these words are the main components of sentences. Then we split 𝑆𝑊 into two sets which satisfy :     
     𝑆𝑊1 ∪ 𝑆𝑊2 = 𝑆𝑊 ,     
     |𝑆𝑊1| = |𝑆𝑊2|."

In [ ]:
def extract_non_stop_words(sentence):
    words = nltk.word_tokenize(sentence)

    stop_words = set(stopwords.words("english"))

    non_stop_words = [word.lower() for word in words if word.lower() not in stop_words and word.isalpha()]

    return non_stop_words

In [ ]:
def split_non_stop_words(non_stop_words):
    m = len(non_stop_words)
    m1 = m // 2
    SW1 = set(non_stop_words[:m1])
    SW2 = set(non_stop_words[m1:])
    return SW1, SW2

In [ ]:
def analyze_sentences(sentences):
    all_SW1 = []
    all_SW2 = []

    for sentence in sentences:
        non_stop_words = extract_non_stop_words(sentence)
        SW1, SW2 = split_non_stop_words(non_stop_words)
        all_SW1.append(SW1)
        all_SW2.append(SW2)

    return all_SW1, all_SW2

In [ ]:
all_SW1, all_SW2 = analyze_sentences(text_data)

for i, sentence in enumerate(text_data):
    print(f"Sentence: {sentence}")
    print(f"SW1: {all_SW1[i]}")
    print(f"SW2: {all_SW2[i]}")
    print("- - - - - - - - - -")

Streaming output truncated to the last 5000 lines.
Sentence: the one thing i wish i ’ d brought travelling with me is multi vitamins ! budget backpacking is not great for getting a balanced diet .
SW1: {'thing', 'brought', 'multi', 'one', 'wish', 'travelling'}
SW2: {'balanced', 'backpacking', 'diet', 'great', 'vitamins', 'budget', 'getting'}
- - - - - - - - - -
Sentence: win a cyberpower  gaming pc plus  fifa   on pc .  ,  ,
SW1: {'win', 'gaming', 'cyberpower'}
SW2: {'plus', 'pc', 'fifa'}
- - - - - - - - - -
Sentence: i cannot wait for halloween        
SW1: {'wait'}
SW2: {'halloween'}
- - - - - - - - - -
Sentence: thought i ' d be a sheep . it ' s yanny for me
SW1: {'thought'}
SW2: {'sheep', 'yanny'}
- - - - - - - - - -
Sentence: bored of all these manager rumors .  viera , arteta and gerrard ? are these the guys to replace rafa or mo diame ?  nufc
SW1: {'viera', 'rumors', 'bored', 'gerrard', 'arteta', 'manager'}
SW2: {'guys', 'diame', 'rafa', 'nufc', 'mo', 'replace'}
- - - - - - - - 

In [ ]:
df["SW1"] = all_SW1
df["SW2"] = all_SW2
df

text    class  \
0     why do small shouldered tiny guys wear huge t ...  notsarc   
1     good morning , please go and vote !  it only t...  notsarc   
2     is it even christmas if there isn ’ t a fight ...     sarc   
3     helping mum with her maths work for the course...  notsarc   
4     dear customer  i am sorry that the mobile phon...  notsarc   
...                                                 ...      ...   
3998  imagine that it ' s going to cost me  pound to...  notsarc   
3999  people really out here tryna argue you do not ...  notsarc   
4000  and their relentless running game , on the bri...  notsarc   
4001  why is it that whether i get out of bed at  or...  notsarc   
4002  honestly this morning ’ s news about gavin and...  notsarc   

                                   PW                       NW  \
0           {shirt, huge, wear, tiny}                       {}   
1     {victory, party, turnout, good}                    {low}   
2           {christmas, fight, wrist}                 {broken}   
3         {work, slowly, math, great}                    {mum}   
4                      {better, hope}          {fucked, sorry}   
...                               ...                      ...   
3998         {travel, imagine, pound}                   {cost}   
3999                               {}                  {argue}   
4000                  {army, running}  {dangerous, relentless}   
4001                               {}                       {}   
4002  {honestly, thrilled, favourite}             {television}   

                                                    SW1  \
0                             {shouldered, tiny, small}   
1     {minutes, please, takes, go, good, morning, vote}   
2                              {even, christmas, fight}   
3                   {maths, course, work, helping, mum}   
4     {bunch, fucked, mobile, customer, dear, sorry,...   
...                                                 ...   
3998                             {going, imagine, cost}   
3999                            {tryna, people, really}   
4000      {brink, running, upsetting, relentless, game}   
4001                        {whether, always, get, bed}   
4002  {stacey, day, honestly, beaming, news, morning...   

                                                    SW2  
0                            {shirts, huge, guys, wear}  
1     {hand, low, turnout, e, uelections, victory, p...  
2                           {wrist, broken, neighbours}  
3             {maths, slowly, great, realising, taking}  
4     {hope, earned, gets, business, sheisters, futu...  
...                                                 ...  
3998                  {travel, pound, university, year}  
3999                      {sanitary, argue, soap, need}  
4000       {army, ground, dangerous, well, knows, game}  
4001                  {get, clock, kitchen, downstairs}  
4002  {favourite, time, series, television, another,...  

[4003 rows x 6 columns]

## 3)
"Here, 𝑃𝑊 ∪ 𝑆𝑊1 and 𝑁𝑊 ∪ 𝑆𝑊2 are used to mask original sentence respectively. So, we will obtain two masked sentences     
𝑥𝑚1 = { [𝑚]1, 𝑥2, ..., [𝑚]𝑛} and     
𝑥𝑚2 = {𝑥1, [𝑚]2, ..., 𝑥𝑛}."

In [ ]:
def construct_union(sentences, PW, NW, all_SW1, all_SW2):
    union_PW_SW1 = []
    union_NW_SW2 = []

    for i, sentence in enumerate(sentences):
        SW1 = all_SW1[i]
        SW2 = all_SW2[i]

        union_PW_SW1.append(PW[i].union(SW1))
        union_NW_SW2.append(NW[i].union(SW2))

    return union_PW_SW1, union_NW_SW2

In [ ]:
union_PW_SW1, union_NW_SW2 = construct_union(text_data, positive_words, negative_words, all_SW1, all_SW2)
print(union_PW_SW1)
print(union_NW_SW2)

[{'huge', 'wear', 'tiny', 'small', 'shouldered', 'shirt'}, {'minutes', 'please', 'turnout', 'victory', 'takes', 'party', 'go', 'good', 'morning', 'vote'}, {'fight', 'wrist', 'even', 'christmas'}, {'maths', 'slowly', 'great', 'course', 'work', 'helping', 'mum', 'math'}, {'bunch', 'hope', 'fucked', 'mobile', 'customer', 'dear', 'sorry', 'phone', 'better', 'reseller', 'mall'}, {'anyone', 'writing', 'review', 'fancy'}, {'abuse', 'hard', 'investigation', 'one', 'poignant', 'ladonna', 'power', 'important', 'sad', 'episode', 'investigations'}, {'middle', 'women', 'aged'}, {'tobias', 'spot', 'swing', 'arrived', 'baby', 'spring', 'taking'}, {'atmos', 'beloved', 'understand', 'decision', 'make'}, {'sad', 'young', 'shit'}, {'find', 'range', 'doe', 'xmas', 'cheese', 'anybody', 'footballs', 'south'}, {'night', 'fall', 'bathroom', 'sound'}, {'americans', 'prepare', 'well', 'downgrade'}, {'snacks', 'snack', 'vegans', 'deodorant', 'lots', 'lavender', 'ft'}, {'w', 'really', 'struggling'}, {'walking', '

In [ ]:
df["union_PW_SW1"] = union_PW_SW1
df["union_NW_SW2"] = union_NW_SW2
df

text    class  \
0     why do small shouldered tiny guys wear huge t ...  notsarc   
1     good morning , please go and vote !  it only t...  notsarc   
2     is it even christmas if there isn ’ t a fight ...     sarc   
3     helping mum with her maths work for the course...  notsarc   
4     dear customer  i am sorry that the mobile phon...  notsarc   
...                                                 ...      ...   
3998  imagine that it ' s going to cost me  pound to...  notsarc   
3999  people really out here tryna argue you do not ...  notsarc   
4000  and their relentless running game , on the bri...  notsarc   
4001  why is it that whether i get out of bed at  or...  notsarc   
4002  honestly this morning ’ s news about gavin and...  notsarc   

                                   PW                       NW  \
0           {shirt, huge, wear, tiny}                       {}   
1     {victory, party, turnout, good}                    {low}   
2           {christmas, fight, wrist}                 {broken}   
3         {work, slowly, math, great}                    {mum}   
4                      {better, hope}          {fucked, sorry}   
...                               ...                      ...   
3998         {travel, imagine, pound}                   {cost}   
3999                               {}                  {argue}   
4000                  {army, running}  {dangerous, relentless}   
4001                               {}                       {}   
4002  {honestly, thrilled, favourite}             {television}   

                                                    SW1  \
0                             {shouldered, tiny, small}   
1     {minutes, please, takes, go, good, morning, vote}   
2                              {even, christmas, fight}   
3                   {maths, course, work, helping, mum}   
4     {bunch, fucked, mobile, customer, dear, sorry,...   
...                                                 ...   
3998                             {going, imagine, cost}   
3999                            {tryna, people, really}   
4000      {brink, running, upsetting, relentless, game}   
4001                        {whether, always, get, bed}   
4002  {stacey, day, honestly, beaming, news, morning...   

                                                    SW2  \
0                            {shirts, huge, guys, wear}   
1     {hand, low, turnout, e, uelections, victory, p...   
2                           {wrist, broken, neighbours}   
3             {maths, slowly, great, realising, taking}   
4     {hope, earned, gets, business, sheisters, futu...   
...                                                 ...   
3998                  {travel, pound, university, year}   
3999                      {sanitary, argue, soap, need}   
4000       {army, ground, dangerous, well, knows, game}   
4001                  {get, clock, kitchen, downstairs}   
4002  {favourite, time, series, television, another,...   

                                           union_PW_SW1  \
0          {huge, wear, tiny, small, shouldered, shirt}   
1     {minutes, please, turnout, victory, takes, par...   
2                       {fight, wrist, even, christmas}   
3     {maths, slowly, great, course, work, helping, ...   
4     {bunch, hope, fucked, mobile, customer, dear, ...   
...                                                 ...   
3998              {travel, imagine, pound, going, cost}   
3999                            {tryna, people, really}   
4000  {army, relentless, game, brink, upsetting, run...   
4001                        {whether, always, get, bed}   
4002  {morning, favourite, stacey, day, honestly, ne...   

                                           union_NW_SW2  
0                            {shirts, huge, guys, wear}  
1     {hand, low, turnout, e, uelections, victory, p...  
2                           {neighbours, broken, wrist}  
3        {realising, mum, maths, taking, slowly, great}  
4     {hope, fucked, ear

In [ ]:
import random

def mask_sentence(sentence, max_mask_count=5):
    words = sentence.split()
    mask_count = min(max_mask_count, len(words))
    mask_indices = random.sample(range(len(words)), mask_count)

    masked_sentence = [
        "<mask>" if i in mask_indices else word
        for i, word in enumerate(words)
    ]

    return " ".join(masked_sentence)


In [ ]:
def construct_masked_sentences(sentences, max_mask_count=5):
    masked_rand_sentences = []

    for sentence in sentences:
        masked_rand_sentence = mask_sentence(sentence, max_mask_count)
        masked_rand_sentences.append(masked_rand_sentence)

    return masked_rand_sentences

In [ ]:
masked_rand_sentences = construct_masked_sentences(text_data)

for i, sentence in enumerate(text_data):
    print(f"Original Sentence: {sentence}")
    print(f"Masked Rand Sentence: {masked_rand_sentences[i]}")
    print("- - - - - - - - - -")

Streaming output truncated to the last 5000 lines.
Masked Rand Sentence: tim lovejoy looks absolutely ancient <mask> <mask> beard must be <mask> to <mask> for the lack of hair on <mask> head .
- - - - - - - - - -
Original Sentence: life is not about waiting for the storm to pass , it ' s about learning to run outside as fast as humanly possible to get the washing in because bloody hell brenda i can not believe the weather we are having in august , can you ? !
Masked Rand Sentence: life is not about waiting for the storm to pass , it ' s about learning <mask> <mask> outside as fast as humanly possible to get the washing in because bloody hell brenda i can not believe the weather <mask> are having in august , <mask> you <mask> !
- - - - - - - - - -
Original Sentence: a frisbee is a hot commodity at a time like this .
Masked Rand Sentence: a <mask> is a <mask> commodity at <mask> <mask> <mask> this .
- - - - - - - - - -
Original Sentence: i have just redeemed my  for  love 2shop high stre

In [ ]:
dfnew = pd.DataFrame({"text": text_data_original, "maskedRandSentence": masked_rand_sentences})
dfnew

text  \
0     why do small shouldered tiny guys wear huge t ...   
1     good morning , please go and vote !  it only t...   
2     is it even christmas if there isn ’ t a fight ...   
3     helping mum with her maths work for the course...   
4     dear customer  i am sorry that the mobile phon...   
...                                                 ...   
3998  imagine that it ' s going to cost me  pound to...   
3999  people really out here tryna argue you do not ...   
4000  and their relentless running game , on the bri...   
4001  why is it that whether i get out of bed at  or...   
4002  honestly this morning ’ s news about gavin and...   

                                     maskedRandSentence  
0     <mask> do <mask> shouldered <mask> guys <mask>...  
1     good morning , please go and vote ! <mask> <ma...  
2     is it even <mask> if there isn <mask> t a figh...  
3     helping mum with her <mask> work for the cours...  
4     <mask> customer i am sorry <mask> the <mask> p...  
...                                                 ...  
3998  imagine that it <mask> s going <mask> cost me ...  
3999  people really <mask> here tryna argue <mask> <...  
4000  and their <mask> running game <mask> on the br...  
4001  why is <mask> that whether <mask> <mask> out o...  
4002  honestly <mask> morning ’ s news about gavin a...  

[4003 rows x 2 columns]

## 4)
"These two masked sentences are fed into the pre-trained generation model to fulfill the generation procedure.     
𝑨{𝑎1, ..., 𝑥2, ..., 𝑥𝑛−1, ..., 𝑎𝑜 } = 𝐵𝐴𝑅𝑇 ( [𝑚]1, 𝑥2, ..., 𝑥𝑛−1, [𝑚]𝑛 )----(1)  
Thus, we will obtain two reborn sentences     
𝐴 = {𝑎1, 𝑎2, ..., 𝑎𝑜 } and     
𝐵 = {𝑏1, 𝑏2, ..., 𝑏𝑝 }."

In [ ]:
%pip install transformers

In [ ]:
def generate_reborn_sentences(masked_sentences):
    tokenizer = BartTokenizer.from_pretrained("facebook/bart-base")
    model = BartForConditionalGeneration.from_pretrained("facebook/bart-base")

    i = 0
    reborn_sentences = []
    for masked_sentence in masked_sentences:
        inputs = tokenizer(masked_sentence, return_tensors="pt")
        generated_encoded = model.generate(inputs['input_ids'])
        reborn_sentence = tokenizer.batch_decode(generated_encoded, skip_special_tokens=True)[0]
        reborn_sentences.append(reborn_sentence)
        i = i + 1
        if (i % 100 == 0):
            print(f'Processed {i} sentences')

    return reborn_sentences

In [ ]:
from google.colab import userdata
userdata.get('HF_TOKEN')

'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'

In [ ]:
import os
os.environ["HF_TOKEN"] = "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"

In [ ]:
reborn_rand_sentences = generate_reborn_sentences(masked_rand_sentences)

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.72k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/558M [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py:1249: UserWarning: Using the model-agnostic default `max_length` (=20) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(


Processed 100 sentences
Processed 200 sentences
Processed 300 sentences
Processed 400 sentences
Processed 500 sentences
Processed 600 sentences
Processed 700 sentences
Processed 800 sentences
Processed 900 sentences
Processed 1000 sentences
Processed 1100 sentences
Processed 1200 sentences
Processed 1300 sentences
Processed 1400 sentences
Processed 1500 sentences
Processed 1600 sentences
Processed 1700 sentences
Processed 1800 sentences
Processed 1900 sentences
Processed 2000 sentences
Processed 2100 sentences
Processed 2200 sentences
Processed 2300 sentences
Processed 2400 sentences
Processed 2500 sentences
Processed 2600 sentences
Processed 2700 sentences
Processed 2800 sentences
Processed 2900 sentences
Processed 3000 sentences
Processed 3100 sentences
Processed 3200 sentences
Processed 3300 sentences
Processed 3400 sentences
Processed 3500 sentences
Processed 3600 sentences
Processed 3700 sentences
Processed 3800 sentences
Processed 3900 sentences
Processed 4000 sentences


In [ ]:
print("Reborn Sentences for Masked Random Sentences:")
for i, reborn_sentence in enumerate(reborn_rand_sentences):
    print(f"Reborn Sentence {i + 1}: {reborn_sentence}")

Reborn Sentences for Masked Random Sentences:
Reborn Sentence 1: What do you think shouldered you guys into a huge turd?
Reborn Sentence 2: good morning, please go and vote!The election takes minutes and a low turnout will
Reborn Sentence 3: is it even possible if there isn t a fight between neighbours and the wrist?
Reborn Sentence 4: helping mum with her work for the course she ’s taking and i�
Reborn Sentence 5: Dear customer i am sorry that the guy on the phone with you in the mall fucked
Reborn Sentence 6: Do you fancy writing a review for me? I will not. be. arsed
Reborn Sentence 7: so this episode of ladonna was one of the most poignant and sad investigations of the
Reborn Sentence 8: You are bitchier than most people know
Reborn Sentence 9: baby tobias has arrived! i ’ ll be taking a spot of leave but
Reborn Sentence 10: do not understand decision to make atmos'so limited. What do they have to
Reborn Sentence 11: The young.
Reborn Sentence 12: for anybody who can not find chees

In [ ]:
dfnew["rebornRandSentence"] = reborn_rand_sentences
dfnew

text  \
0     why do small shouldered tiny guys wear huge t ...   
1     good morning , please go and vote !  it only t...   
2     is it even christmas if there isn ’ t a fight ...   
3     helping mum with her maths work for the course...   
4     dear customer  i am sorry that the mobile phon...   
...                                                 ...   
3998  imagine that it ' s going to cost me  pound to...   
3999  people really out here tryna argue you do not ...   
4000  and their relentless running game , on the bri...   
4001  why is it that whether i get out of bed at  or...   
4002  honestly this morning ’ s news about gavin and...   

                                     maskedRandSentence  \
0     <mask> do <mask> shouldered <mask> guys <mask>...   
1     good morning , please go and vote ! <mask> <ma...   
2     is it even <mask> if there isn <mask> t a figh...   
3     helping mum with her <mask> work for the cours...   
4     <mask> customer i am sorry <mask> the <mask> p...   
...                                                 ...   
3998  imagine that it <mask> s going <mask> cost me ...   
3999  people really <mask> here tryna argue <mask> <...   
4000  and their <mask> running game <mask> on the br...   
4001  why is <mask> that whether <mask> <mask> out o...   
4002  honestly <mask> morning ’ s news about gavin a...   

                                     rebornRandSentence  
0     What do you think shouldered you guys into a h...  
1     good morning, please go and vote!The election ...  
2     is it even possible if there isn t a fight bet...  
3     helping mum with her work for the course she ’...  
4     Dear customer i am sorry that the guy on the p...  
...                                                 ...  
3998  imagine that it s going to cost me pound for p...  
3999  people really here tryna argue that we do not ...  
4000  and their potent running game is on the brink ...  
4001  why is it that whether i get out of bed at or,...  
4002  honestly, this morning ’ s news about gavin an...  

[4003 rows x 3 columns]

# Sentences Representation
"We embed the original sentence 𝑥 and its corresponding reborn texts 𝐴 and 𝐵     
into 𝑑-dimentional embedding 𝑯𝑡 ∈ R𝑑     
via pre-trained BERT-base:     
𝑯𝑥, 𝑯𝐴, 𝑯𝐵 = 𝐵𝐸𝑅𝑇 (𝑥), 𝐵𝐸𝑅𝑇 (𝐴), 𝐵𝐸𝑅𝑇 (𝐵)."

In [ ]:
def embed_sentences(sentences):
    tokenizer = AutoTokenizer.from_pretrained("princeton-nlp/sup-simcse-bert-base-uncased")
    model = AutoModel.from_pretrained("princeton-nlp/sup-simcse-bert-base-uncased")

    i = 0
    embeddings = []
    for sentence in sentences:
        inputs = tokenizer(sentence, return_tensors="pt", padding=True, truncation=True)
        with torch.no_grad():
            outputs = model(**inputs).last_hidden_state.mean(dim=1)
        embeddings.append(outputs)
        i = i + 1
        if (i % 100 == 0):
            print(f'Processed {i} sentences')

    return torch.stack(embeddings)

In [ ]:
x_embeddings = embed_sentences(text_data)

A_embeddings = embed_sentences(reborn_rand_sentences)

tokenizer_config.json:   0%|          | 0.00/252 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/689 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/438M [00:00<?, ?B/s]

Processed 100 sentences
Processed 200 sentences
Processed 300 sentences
Processed 400 sentences
Processed 500 sentences
Processed 600 sentences
Processed 700 sentences
Processed 800 sentences
Processed 900 sentences
Processed 1000 sentences
Processed 1100 sentences
Processed 1200 sentences
Processed 1300 sentences
Processed 1400 sentences
Processed 1500 sentences
Processed 1600 sentences
Processed 1700 sentences
Processed 1800 sentences
Processed 1900 sentences
Processed 2000 sentences
Processed 2100 sentences
Processed 2200 sentences
Processed 2300 sentences
Processed 2400 sentences
Processed 2500 sentences
Processed 2600 sentences
Processed 2700 sentences
Processed 2800 sentences
Processed 2900 sentences
Processed 3000 sentences
Processed 3100 sentences
Processed 3200 sentences
Processed 3300 sentences
Processed 3400 sentences
Processed 3500 sentences
Processed 3600 sentences
Processed 3700 sentences
Processed 3800 sentences
Processed 3900 sentences
Processed 4000 sentences
Processed

In [ ]:
for i, sentence in enumerate(text_data):
    print(f"Embedding for Original Lowercase Sentence {i + 1} ({sentence}):")
    print(x_embeddings[i])
    print("- - - - - - - - - -")

Streaming output truncated to the last 5000 lines.
          3.4725e-01, -2.4786e-01, -2.7578e-01, -2.6902e-01, -6.9727e-02,
         -1.0435e-01,  2.9424e-01,  2.7911e-01, -6.7370e-02,  1.4964e-02,
         -8.9923e-02, -1.1077e-01, -6.1527e-02, -3.2078e-02,  1.0491e-01,
         -2.3540e-01, -6.5371e-02,  1.7637e-02,  7.8999e-02,  2.2984e-01,
         -2.9960e-01, -2.3310e-01,  1.8909e-01,  2.2909e-01, -6.2361e-01,
         -2.5710e-01,  4.4839e-02,  9.2926e-02, -1.2252e-01,  7.8538e-02,
         -6.5198e-02,  3.0073e-02, -1.7900e-01]])
- - - - - - - - - -
Embedding for Original Lowercase Sentence 3972 (spent the morning nursing a very hungover daughter , after she came home at some ungodly hour .  oh how times have changed ):
tensor([[ 5.3628e-02,  5.9410e-02,  5.4324e-01, -5.0224e-01,  2.3215e-02,
         -1.9734e-01,  2.9660e-01,  6.2760e-01,  2.0810e-01,  2.5437e-01,
          3.5356e-01, -2.3374e-01, -2.4814e-01,  6.0689e-01, -3.9613e-01,
          2.0445e-01,  5.7425e-01,  1.0

In [ ]:
for i, sentence in enumerate(reborn_rand_sentences):
    print(f"Embedding for Reborn Random Sentence {i + 1} ({sentence}):")
    print(A_embeddings[i])
    print("- - - - - - - - - -")

Streaming output truncated to the last 5000 lines.
          4.7279e-01, -2.9829e-01, -1.4449e-01, -2.5753e-01, -4.3984e-01,
          1.9961e-01,  3.2756e-01,  3.4105e-01,  2.5937e-01,  3.7021e-01,
         -9.0496e-02, -9.2729e-02, -6.1737e-03,  4.1887e-01,  1.5884e-03,
         -1.5693e-01, -3.7412e-01,  1.9548e-01,  1.8450e-04,  2.5662e-01,
         -3.5428e-01, -1.4594e-01, -4.8444e-01,  2.9876e-01, -8.0973e-01,
         -2.0831e-01, -1.2602e-01, -1.3959e-01,  2.5199e-01, -7.6135e-03,
         -5.7483e-02,  1.0866e-02, -3.6116e-01]])
- - - - - - - - - -
Embedding for Reborn Random Sentence 3972 (spent the morning with a hungover daughter, after which she came home at some):
tensor([[ 1.5971e-02, -1.5434e-01,  4.6517e-01, -1.1446e-01, -1.1191e-01,
         -2.6547e-02,  3.8644e-01,  3.4602e-01,  1.7132e-01,  3.6622e-01,
          2.1900e-01,  9.8394e-02, -6.2645e-02,  3.3864e-01, -4.9072e-01,
          6.5988e-02,  6.8435e-01, -4.4863e-02, -2.0287e-02, -1.9442e-01,
          2.9537

In [ ]:
dfnew["xEmbedding"] = x_embeddings.tolist()
dfnew["AEmbedding"] = A_embeddings.tolist()
dfnew

text  \
0     why do small shouldered tiny guys wear huge t ...   
1     good morning , please go and vote !  it only t...   
2     is it even christmas if there isn ’ t a fight ...   
3     helping mum with her maths work for the course...   
4     dear customer  i am sorry that the mobile phon...   
...                                                 ...   
3998  imagine that it ' s going to cost me  pound to...   
3999  people really out here tryna argue you do not ...   
4000  and their relentless running game , on the bri...   
4001  why is it that whether i get out of bed at  or...   
4002  honestly this morning ’ s news about gavin and...   

                                     maskedRandSentence  \
0     <mask> do <mask> shouldered <mask> guys <mask>...   
1     good morning , please go and vote ! <mask> <ma...   
2     is it even <mask> if there isn <mask> t a figh...   
3     helping mum with her <mask> work for the cours...   
4     <mask> customer i am sorry <mask> the <mask> p...   
...                                                 ...   
3998  imagine that it <mask> s going <mask> cost me ...   
3999  people really <mask> here tryna argue <mask> <...   
4000  and their <mask> running game <mask> on the br...   
4001  why is <mask> that whether <mask> <mask> out o...   
4002  honestly <mask> morning ’ s news about gavin a...   

                                     rebornRandSentence  \
0     What do you think shouldered you guys into a h...   
1     good morning, please go and vote!The election ...   
2     is it even possible if there isn t a fight bet...   
3     helping mum with her work for the course she ’...   
4     Dear customer i am sorry that the guy on the p...   
...                                                 ...   
3998  imagine that it s going to cost me pound for p...   
3999  people really here tryna argue that we do not ...   
4000  and their potent running game is on the brink ...   
4001  why is it that whether i get out of bed at or,...   
4002  honestly, this morning ’ s news about gavin an...   

                                             xEmbedding  \
0     [[0.7081335783004761, 0.1210532933473587, -0.5...   
1     [[-0.14586037397384644, -0.6124593019485474, 1...   
2     [[0.08108999580144882, -0.23094923794269562, 0...   
3     [[0.20817291736602783, 0.24460144340991974, 0....   
4     [[0.4123021364212036, 0.09793900698423386, 0.5...   
...                                                 ...   
3998  [[0.37059521675109863, 0.1753413826227188, 0.4...   
3999  [[0.6794640421867371, 0.38444259762763977, -0....   
4000  [[-0.20612402260303497, 0.10531388223171234, -...   
4001  [[0.6105952858924866, 0.4410528838634491, 0.49...   
4002  [[0.526084303855896, -0.21372130513191223, 0.7...   

                                             AEmbedding  
0     [[0.31090405583381653, 0.09994444251060486, -0...  
1     [[0.21031758189201355, -0.09585575759410858, 0...  
2     [[0.3397110402584076, -0.53464674949646, 0.072...  
3     [[0.6202572584152222, 0.135048508644104, 0.353...  
4     [[0.26444104313850403, 0.15712694823741913, 0....  
...                                                 ...  
3998  [[0.3991992771625519, 0.024164792150259018, 0....  
3999  [[0.6400356292724609, 0.4723109006881714, -0.0...  
4000  [[-0.13672849535942078, 0.005846679210662842, ...  
4001  [[0.5307811498641968, 0.00047351655666716397, ...  
4002  [[0.5277367234230042, -0.09742490202188492, 0....  

[4003 rows x 5 columns]

# Sarcastic Utterances Detection
## 1)
"We utilize cosine similarity to measure the similarity between representations of original sentence 𝐻𝑥     
and generation texts 𝐻𝐴/𝐻𝐵.

Then we use the following equation to calculate a difference score of each sentence:     
diff = sim(𝐻𝑥, 𝐻𝐴) < 𝑡ℎ𝑟𝑒𝑠ℎ𝑜𝑙𝑑 || sim(𝐻𝑥, 𝐻𝐵) < 𝑡ℎ𝑟𝑒𝑠ℎ𝑜𝑙𝑑     
where || means "or" logical operator."

In [ ]:
def calculate_difference_scores(x_embeddings, A_embeddings, threshold):
    i = 0
    diff_scores = []
    for x_emb, A_emb in zip(x_embeddings, A_embeddings):
        sim_Hx_HA = cosine_similarity(x_emb, A_emb)

        diff = (sim_Hx_HA < threshold)
        diff_scores.append(diff)
        i = i + 1
        if (i % 100 == 0):
            print(f'Processed {i} embeddings')

    return diff_scores

In [ ]:
threshold = 0.755

diff_scores = calculate_difference_scores(x_embeddings, A_embeddings, threshold)
diff_scores

Processed 100 embeddings
Processed 200 embeddings
Processed 300 embeddings
Processed 400 embeddings
Processed 500 embeddings
Processed 600 embeddings
Processed 700 embeddings
Processed 800 embeddings
Processed 900 embeddings
Processed 1000 embeddings
Processed 1100 embeddings
Processed 1200 embeddings
Processed 1300 embeddings
Processed 1400 embeddings
Processed 1500 embeddings
Processed 1600 embeddings
Processed 1700 embeddings
Processed 1800 embeddings
Processed 1900 embeddings
Processed 2000 embeddings
Processed 2100 embeddings
Processed 2200 embeddings
Processed 2300 embeddings
Processed 2400 embeddings
Processed 2500 embeddings
Processed 2600 embeddings
Processed 2700 embeddings
Processed 2800 embeddings
Processed 2900 embeddings
Processed 3000 embeddings
Processed 3100 embeddings
Processed 3200 embeddings
Processed 3300 embeddings
Processed 3400 embeddings
Processed 3500 embeddings
Processed 3600 embeddings
Processed 3700 embeddings
Processed 3800 embeddings
Processed 3900 embedd

[array([[ True]]),
 array([[False]]),
 array([[False]]),
 array([[False]]),
 array([[False]]),
 array([[False]]),
 array([[False]]),
 array([[False]]),
 array([[False]]),
 array([[False]]),
 array([[ True]]),
 array([[False]]),
 array([[False]]),
 array([[False]]),
 array([[False]]),
 array([[False]]),
 array([[False]]),
 array([[ True]]),
 array([[False]]),
 array([[False]]),
 array([[False]]),
 array([[False]]),
 array([[False]]),
 array([[ True]]),
 array([[False]]),
 array([[False]]),
 array([[False]]),
 array([[ True]]),
 array([[ True]]),
 array([[False]]),
 array([[False]]),
 array([[ True]]),
 array([[False]]),
 array([[False]]),
 array([[ True]]),
 array([[False]]),
 array([[ True]]),
 array([[ True]]),
 array([[False]]),
 array([[ True]]),
 array([[False]]),
 array([[ True]]),
 array([[False]]),
 array([[False]]),
 array([[False]]),
 array([[False]]),
 array([[False]]),
 array([[False]]),
 array([[False]]),
 array([[False]]),
 array([[False]]),
 array([[False]]),
 array([[ Tr

## 2)
"Since the sarcastic utterances are influenced more than normal texts during the masking and generation procedure,     
the difference score of sarcastic texts should be greater than a non-sarcastic one.

If we have a threshold value which separates sarcastic texts and normal texts,     
we can yield the prediction 𝑦 by:     
𝑦 = I(diff)."

In [ ]:
predicted_labels = [int(diff) for diff in diff_scores]
print(predicted_labels)
print(sum(predicted_labels))

[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 

<ipython-input-51-82d9077db80e>:1: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predicted_labels = [int(diff) for diff in diff_scores]


In [ ]:
labels = ["sarc" if diff else "notsarc" for diff in diff_scores]
print(labels)

['sarc', 'notsarc', 'notsarc', 'notsarc', 'notsarc', 'notsarc', 'notsarc', 'notsarc', 'notsarc', 'notsarc', 'sarc', 'notsarc', 'notsarc', 'notsarc', 'notsarc', 'notsarc', 'notsarc', 'sarc', 'notsarc', 'notsarc', 'notsarc', 'notsarc', 'notsarc', 'sarc', 'notsarc', 'notsarc', 'notsarc', 'sarc', 'sarc', 'notsarc', 'notsarc', 'sarc', 'notsarc', 'notsarc', 'sarc', 'notsarc', 'sarc', 'sarc', 'notsarc', 'sarc', 'notsarc', 'sarc', 'notsarc', 'notsarc', 'notsarc', 'notsarc', 'notsarc', 'notsarc', 'notsarc', 'notsarc', 'notsarc', 'notsarc', 'sarc', 'notsarc', 'sarc', 'notsarc', 'notsarc', 'sarc', 'notsarc', 'notsarc', 'notsarc', 'notsarc', 'notsarc', 'notsarc', 'notsarc', 'sarc', 'sarc', 'notsarc', 'notsarc', 'sarc', 'notsarc', 'notsarc', 'notsarc', 'notsarc', 'notsarc', 'notsarc', 'notsarc', 'notsarc', 'notsarc', 'notsarc', 'notsarc', 'sarc', 'notsarc', 'notsarc', 'sarc', 'notsarc', 'notsarc', 'sarc', 'notsarc', 'sarc', 'sarc', 'notsarc', 'notsarc', 'notsarc', 'sarc', 'notsarc', 'sarc', 'notsar

In [ ]:
dffinal = pd.DataFrame({"text": text_data, "class": label_data, "prediction": labels})
dffinal

text    class prediction
0     why do small shouldered tiny guys wear huge t ...  notsarc       sarc
1     good morning , please go and vote !  it only t...  notsarc    notsarc
2     is it even christmas if there isn ’ t a fight ...     sarc    notsarc
3     helping mum with her maths work for the course...  notsarc    notsarc
4     dear customer  i am sorry that the mobile phon...  notsarc    notsarc
...                                                 ...      ...        ...
3998  imagine that it ' s going to cost me  pound to...  notsarc    notsarc
3999  people really out here tryna argue you do not ...  notsarc    notsarc
4000  and their relentless running game , on the bri...  notsarc    notsarc
4001  why is it that whether i get out of bed at  or...  notsarc    notsarc
4002  honestly this morning ’ s news about gavin and...  notsarc    notsarc

[4003 rows x 3 columns]

# Main Experiment Results

In [ ]:
true_labels = [1 if pred == "sarc" else 0 for pred in df["class"]]
print(true_labels)
print(predicted_labels)

accuracy = accuracy_score(true_labels, predicted_labels)
precision = precision_score(true_labels, predicted_labels)
f1 = f1_score(true_labels, predicted_labels)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("F1 Score:", f1)

[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [ ]:
conf_matrix = confusion_matrix(true_labels, predicted_labels)

print("Confusion Matrix:")
print(conf_matrix)

Confusion Matrix:
[[2466  831]
 [ 497  209]]
